In [2]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [3]:
# question 1

a1 = np.arange (1,11).reshape(2,5)
print(a1)
print(a1.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
(2, 5)


In [6]:
# question 2

a2= np.arange(1,21)
a2
a2[5:15]

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [9]:
import pandas as pd

In [10]:
# question 3

fruit = pd.Series ({'apples': 3, 'bananas': 2, 'oranges': 1})
print(fruit)
fruit["pears"] = 4
print(fruit)

apples     3
bananas    2
oranges    1
dtype: int64
apples     3
bananas    2
oranges    1
pears      4
dtype: int64


In [11]:
# question 4

data = {
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Mike', 'Emily', 'David', 'Sarah', 'Kevin', 'Jessica'],
    'age': [25, 31, 42, 29, 35, 28, 40, 38, 45, 32],
    'gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male', 'Female']
}

df = pd.DataFrame(data)

print(df)


      name  age  gender
0     John   25    Male
1     Anna   31  Female
2    Peter   42    Male
3    Linda   29  Female
4     Mike   35    Male
5    Emily   28  Female
6    David   40    Male
7    Sarah   38  Female
8    Kevin   45    Male
9  Jessica   32  Female


In [12]:
# question 5

df['occupation'] = ['Programmer', 'Manager', 'Analyst', 'Manager', 'Programmer', 'Analyst', 'Manager', 'Analyst', 'Programmer', 'Analyst']
df

name  age  gender  occupation
0     John   25    Male  Programmer
1     Anna   31  Female     Manager
2    Peter   42    Male     Analyst
3    Linda   29  Female     Manager
4     Mike   35    Male  Programmer
5    Emily   28  Female     Analyst
6    David   40    Male     Manager
7    Sarah   38  Female     Analyst
8    Kevin   45    Male  Programmer
9  Jessica   32  Female     Analyst

In [17]:
# question 6

filtered_age = df[df['age'] >= 30]
filtered_age

name  age  gender  occupation
1     Anna   31  Female     Manager
2    Peter   42    Male     Analyst
4     Mike   35    Male  Programmer
6    David   40    Male     Manager
7    Sarah   38  Female     Analyst
8    Kevin   45    Male  Programmer
9  Jessica   32  Female     Analyst

In [18]:
# question 7

df.to_csv('workers.csv', index = False)
print("df saved as 'workers.csv'.")
df_csv= pd.read_csv('workers.csv')
print(df_csv)

df saved as 'workers.csv'.
      name  age  gender  occupation
0     John   25    Male  Programmer
1     Anna   31  Female     Manager
2    Peter   42    Male     Analyst
3    Linda   29  Female     Manager
4     Mike   35    Male  Programmer
5    Emily   28  Female     Analyst
6    David   40    Male     Manager
7    Sarah   38  Female     Analyst
8    Kevin   45    Male  Programmer
9  Jessica   32  Female     Analyst
